//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAI_1_9_EF_DATABASE_FIRST
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonhangChitiet
    {
        public int DonhangChitietID { get; set; }
        public Nullable<int> DonhangID { get; set; }
        public Nullable<int> SanphamID { get; set; }
        public Nullable<int> Soluong { get; set; }
    }
}
