//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAI_1_9_EF_DATABASE_FIRST
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donhang
    {
        public int DonhangID { get; set; }
        public Nullable<int> KhachhangID { get; set; }
        public Nullable<int> NhanvienID { get; set; }
        public Nullable<System.DateTime> Ngaydathang { get; set; }
        public Nullable<int> ShipperID { get; set; }
    }
}
