//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAI_1_9_EF_DATABASE_FIRST
{
    using System;
    using System.Collections.Generic;
    
    public partial class Khachhang
    {
        public int KhachhangID { get; set; }
        public string HoTen { get; set; }
        public string TenLienLac { get; set; }
        public string Diachi { get; set; }
        public string Thanhpho { get; set; }
        public string MaBuudien { get; set; }
        public string QuocGia { get; set; }
    }
}
